[package]
name = "primitive_enum"
version = "1.0.0"
authors = ["math4tots <math4tots@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
